name: aptagrow
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - viennarna=2.4.18
  - numpy=1.23.5
  - scipy=1.10.1
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - matplotlib=3.7.2
  - pillow=10.0.1
  - pymol-open-source=2.5.4
  - pyyaml=6.0.1
  - tqdm=4.66.1
  - hdbscan=0.8.33
  - umap-learn=0.5.5
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pip
  - pip:
      - torch-geometric==2.3.1
      - pytest==7.4.4
